import type { T_MinimalDropdownOption } from "./Input.types"

export const IranPlateNumberLetterOptions: T_MinimalDropdownOption[] = [
    { labelKey: "f", value: "f" },
    { labelKey: "b", value: "b" },
    { labelKey: "j", value: "j" },
    { labelKey: "d", value: "d" },
    { labelKey: "s", value: "s" },
    { labelKey: "c", value: "c" },
    { labelKey: "t", value: "t" },
    { labelKey: "q", value: "q" },
    { labelKey: "l", value: "l" },
    { labelKey: "m", value: "m" },
    { labelKey: "n", value: "n" },
    { labelKey: "v", value: "v" },
    { labelKey: "h", value: "h" },
    { labelKey: "y", value: "y" },
    { labelKey: "H", value: "H" },
    { labelKey: "T", value: "T" },
    { labelKey: "A", value: "A" },
    { labelKey: "P", value: "P" },
    { labelKey: "C", value: "C" },
    { labelKey: "M", value: "M" },
    { labelKey: "Z", value: "Z" },
    { labelKey: "F", value: "F" },
    { labelKey: "K", value: "K" },
    { labelKey: "G", value: "G" },
    { labelKey: "D", value: "D" },
    { labelKey: "S", value: "S" },
]
